import {
  BarChart3,
  Briefcase,
  FileText,
  Folder,
  Gavel,
  HandCoins,
  Headset,
  Home,
  IdCard,
  Landmark,
  Layers,
  LayoutGrid,
  LifeBuoy,
  MessageCircle,
  Package,
  Plug,
  Scale,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  UserRound,
  Users,
  Wallet,
  Bell,
  type LucideIcon,
} from "lucide-react";
import type { NavIcon } from "@/lib/nav";

export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  home: Home,
  platform: LayoutGrid,
  products: Package,
  quotes: FileText,
  policies: ShieldCheck,
  documents: Folder,
  underwriting: Scale,
  claims: LifeBuoy,
  collections: Wallet,
  accounting: Landmark,
  fraud: ShieldAlert,
  apis: Plug,
  channels: MessageCircle,
  agency: Users,
  broker: Briefcase,
  ai: Sparkles,
  analytics: BarChart3,
  regulatory: Gavel,
  surplus: HandCoins,
  reinsurance: Layers,
  selfService: UserRound,
  crm: Headset,
  notifications: Bell,
  profile: IdCard,
  admin: Settings,
};
